### ISSUE TITLE
Removal of globalemu.

### ISSUE THREAD

**Issue by htjb** [georgestein/ml-in-cosmology#3]
Hi,

I think globalemu (https://arxiv.org/abs/2104.04336) may have been removed from the `Reionization and 21cm` section in the latest commit (53684359d60a653b8f409ef2c0dfbe721c485a6f). The paper was added in in PR #2. Would it be possible to added it back onto the list please?

Thanks,
Harry

**Comment by georgestein** [comment]
Whoops sorry about that! Its back up now

**Comment by htjb** [comment]
@georgestein Thanks!
